### ISSUE TITLE
Bookmarklet runs into CSP error

### ISSUE THREAD

**Issue by abritinthebay** [paulirish/memory-stats.js#21]
Trying to run it results in:

> Refused to load the script 'https://rawgit.com/paulirish/memory-stats.js/master/bookmarklet.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".

So sad :cry:

**Comment by malyw** [comment]
The same problem.
Environment:
Os X Yosemite, Chrome stable and Chrome Canary- both throw that error when trying to run as bookmarklet.

**Comment by paulirish** [comment]
I don't think there's a way around it.

https://bugzilla.mozilla.org/show_bug.cgi?id=866522
https://code.google.com/p/chromium/issues/detail?id=233903

**Comment by abritinthebay** [comment]
Would loading it via script tag injection not get around this?
