### ISSUE TITLE
Cannot see the graph in memory tracking

### ISSUE THREAD

**Issue by tiansijie** [paulirish/memory-stats.js#22]
I got the demo running, but I cannot see the graph. The number is updating correctly. Not sure if I set it up correctly.

![screen shot 2015-02-18 at 3 05 18 pm](https://cloud.githubusercontent.com/assets/3675602/6255633/9ebac56e-b77f-11e4-9224-2ece73859c23.png)

**Comment by gordlea** [comment]
Same here. I'm using the bookmarklet.

![nograph](https://cloud.githubusercontent.com/assets/782154/6276498/3128b642-b83c-11e4-8cad-4304fc5ecdf6.png)

**Comment by paulirish** [comment]
give it another go. we've just updated the source pretty substantially.

**Comment by gordlea** [comment]
Fixed for me. Thank you!
