### ISSUE TITLE
Link to angular module is broken

### ISSUE THREAD

**Issue by lc-nyovchev** [paulirish/memory-stats.js#32]
Maybe re-link to: https://github.com/myagoo/angular-memory-stats or https://github.com/shprink/angular-performance-stats

**Comment by paulirish** [comment]
you tell me which one. :)

**Comment by lc-nyovchev** [comment]
Ah, that's why I made the issue :) Don''t know which one is closer to the original. Seems like the first one but maybe it's a good idea to link the second one as well?

**Comment by paulirish** [comment]
https://github.com/myagoo/angular-memory-stats seems dead.

<hr>

@shprink i'm going to link to your repo

can you confirm that https://github.com/shprink/angular-performance-stats is now more canonical than the more starred https://github.com/livingobjects/angular-memory-stats one?

seems you own both.. so which one is good?

**Comment by shprink** [comment]
https://github.com/livingobjects/angular-memory-stats is the one :) The other one is just sone tests for now.

Thanks

**Comment by shprink** [comment]
https://github.com/paulirish/memory-stats.js/pull/35

**Comment by paulirish** [comment]
you rock. thanks.
